Update systemctl-inst

diff --git a/bin/systemctl-inst b/bin/systemctl-inst
--- a/bin/systemctl-inst
+++ b/bin/systemctl-inst
@@ -2,43 +2,32 @@
 ## Looks into current Folder installs systemd *.service files accepts path as arg
 shopt -s nullglob
 # shopt -s dotglob # To include hidden files
-files=(${1}/*.service)
 if [ ! -z "$1" ]; 
  then
+  files=(${1}/*.service)
   # Check if we find service files in this dir
   if [ ${#files[@]} -gt 0 ]; 
    then 
     cd $1; 
-    echo "Installing $(echo ls *.service) from $PWD"; 
-    # Removing old if exist
-    ls *.service | xargs -i -n1 rm /lib/systemd/system/{}
-    ls *.service | xargs -i -n1 find /etc/systemd -name "{}" -print0 | xargs -0 rm
-    # Installing services into systemd repo
-    ln -s ${PWD}/*.service  /lib/systemd/system;
-    systemctl daemon-reload;
-    # Activating
-    ls *.service | xargs -n1 systemctl enable
-    systemctl daemon-reload;
-   else 
-    echo "Sorry no *.service files in $1"; 
-    exit 1;
+   else
+     echo "Failed: no systemd services found in $1 \n usage: systemctl-inst /path/to/*.service files or or move into the dir i tested current $PWD";
+     exit 1
   fi;
- else
+fi;
+
   # Check if we find service files in current dir
   files=(${PWD}/*.service)
   if [ ${#files[@]} -gt 0 ]; 
    then 
-    echo "Installing $(echo ls *.service) from $PWD";
+    echo "Installing $(echo $(ls *.service)) from $PWD to /lib/systemd/system";
     # Removing old if exist
-    ls *.service | xargs -i -n1 rm /lib/systemd/system/{}
-    ls *.service | xargs -i -n1 find /etc/systemd -name "{}" -print0 | xargs -0 rm
+    ls *.service | xargs -i -n1 rm -f /lib/systemd/system/{}
+    ls *.service | xargs -i -n1 find /etc/systemd -name "{}" -print0 | xargs -0 rm -f
     # Installing services into systemd repo
-    ln -s ${PWD}/*.service  /lib/systemd/system;
+    rsync -Avzh --progress ${PWD}/*.service  /lib/systemd/system;
     systemctl daemon-reload;
     # Activating
     ls *.service | xargs -n1 systemctl enable
     systemctl daemon-reload;
     exit 0; 
-   fi;
- echo "Failed: no systemd services found \n usage systemctl-inst /path/to/*.service files or or move into the dir i tested current $PWD "
-fi;
+  fi;
